version: '3.5'

services:
  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"
    networks:
      - iceHorseNet
  redisCommander:
    container_name: redis_commander
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
     - REDIS_HOSTS=local:redis:6379
    networks:
      - iceHorseNet      
  postgres:
    container_name: postgres_container
    image: mdillon/postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: iceHorseFair
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
       - postgres:/data/postgres
    command:
       - "postgres"
       - "-c"
       - "shared_preload_libraries=pg_stat_statements"   
    ports:
      - "5432:5432"
    networks:
      - iceHorseNet
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - iceHorseNet
    restart: unless-stopped

networks:
  iceHorseNet:
    driver: bridge

volumes:
    postgres:
    pgadmin: